"""Capstone: Cymbal Stadiums Marketing Content Studio.

The real use case this whole repo builds toward. A comms team member
gives it a raw idea; it comes back with an approved, on-brand slide copy,
localized into three languages, plus a matching poster illustration --
generated by asking a completely separate agent process for it.

It's built by composing four of the patterns you've already seen, each
used for exactly the job it's good at:

    1. Sequential draft    (pattern 2) -- gather facts, then write. Fixed order.
    2. Loop critic/reviser (pattern 4) -- refine until on-brand, capped iterations.
    3. Parallel fan-out    (pattern 3) -- localize into 3 languages at once.
    4. Agent-to-agent call (pattern 6) -- ask a separately-running illustration
       agent, over HTTP, for a poster.

This is what a "real" agentic system tends to look like in practice: not
one exotic pattern, but several simple, well-understood ones, composed.

Before running this, start the illustration agent in another terminal
(from the repo root):
    PYTHONPATH=. uvicorn illustration_agent_service:app \\
        --app-dir patterns/06_agent_to_agent_http --port 8001

Then, in a second terminal, from the repo root:
    PYTHONPATH=. python capstone/marketing_content_studio/studio.py
    PYTHONPATH=. python capstone/marketing_content_studio/studio.py "your topic here" external
"""

from __future__ import annotations

import json
import os
import sys
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

import httpx  # noqa: E402
from dotenv import load_dotenv  # noqa: E402

from common import llm, tracing  # noqa: E402
from common.cymbal_tools import lookup_audience_persona, lookup_brand_guidelines  # noqa: E402

load_dotenv()

ILLUSTRATION_AGENT_URL = os.getenv("ILLUSTRATION_AGENT_URL", "http://localhost:8001")
LANGUAGES = {"es": "Spanish", "fr": "French", "de": "German"}
MAX_CRITIQUE_ITERATIONS = 3
OUTPUT_DIR = Path(__file__).resolve().parent / "output"


# --- Stage 1/4: sequential draft (pattern 2) --------------------------------


def _mock_writer(messages, tools, system) -> llm.LLMResponse:
    return llm.LLMResponse(
        text="Our team does a really great job with on-the-job training and we are very proud of it."
    )


def research_and_draft(topic: str, audience: str) -> str:
    tracing.step("studio", f"stage 1/4: sequential research + draft (topic={topic!r})")
    guidelines = lookup_brand_guidelines(topic)
    persona = lookup_audience_persona(audience)
    prompt = (
        f"Topic: {topic}\nBrand guidelines: {guidelines}\nAudience persona: {persona['persona']}\n\n"
        "Write a 1-2 sentence slide body that follows the brand voice above."
    )
    response = llm.chat([{"role": "user", "content": prompt}], mock_fn=_mock_writer)
    return response.text or ""


# --- Stage 2/4: loop critic/reviser (pattern 4) -----------------------------


def _mock_critic(messages, tools, system) -> llm.LLMResponse:
    draft = messages[-1]["content"]
    if "wrench" in draft.lower():
        return llm.LLMResponse(text="APPROVE: concrete and on-brand.")
    return llm.LLMResponse(text="REVISE: too generic -- ground it in a concrete image from our maintenance work.")


def _mock_reviser(messages, tools, system) -> llm.LLMResponse:
    return llm.LLMResponse(
        text=(
            "Every wrench we hand a trainee keeps a stadium game-ready -- our on-the-job "
            "training turns new hires into the crew that never lets fans down."
        )
    )


def critique_and_revise(draft: str) -> str:
    tracing.step("studio", "stage 2/4: loop critique/revise")
    for iteration in range(1, MAX_CRITIQUE_ITERATIONS + 1):
        verdict_prompt = f"Review this slide copy. Respond 'APPROVE: ...' or 'REVISE: ...':\n\n{draft}"
        verdict = llm.chat([{"role": "user", "content": verdict_prompt}], mock_fn=_mock_critic).text or ""
        tracing.tool_result("critic", "verdict", verdict)
        if verdict.upper().startswith("APPROVE"):
            tracing.step("studio", f"approved after {iteration} iteration(s)")
            return draft
        feedback = verdict.split(":", 1)[-1].strip()
        revise_prompt = f"Draft:\n{draft}\n\nFeedback:\n{feedback}\n\nRewrite it."
        draft = llm.chat([{"role": "user", "content": revise_prompt}], mock_fn=_mock_reviser).text or draft
    tracing.step("studio", f"hit MAX_CRITIQUE_ITERATIONS={MAX_CRITIQUE_ITERATIONS}, using best effort")
    return draft


# --- Stage 3/4: parallel fan-out (pattern 3) --------------------------------


def _mock_translator(lang_name: str):
    def responder(messages, tools, system) -> llm.LLMResponse:
        return llm.LLMResponse(text=f"[{lang_name}] {messages[-1]['content']}")

    return responder


def _translate_one(text: str, lang_code: str) -> str:
    lang_name = LANGUAGES[lang_code]
    prompt = f"Translate into {lang_name}, keep it concise:\n\n{text}"
    return llm.chat([{"role": "user", "content": prompt}], mock_fn=_mock_translator(lang_name)).text or ""


def localize(approved_draft: str) -> dict[str, str]:
    tracing.step("studio", f"stage 3/4: parallel localization into {list(LANGUAGES)}")
    results: dict[str, str] = {}
    with ThreadPoolExecutor(max_workers=len(LANGUAGES)) as pool:
        futures = {pool.submit(_translate_one, approved_draft, code): code for code in LANGUAGES}
        for future in as_completed(futures):
            results[futures[future]] = future.result()
    return results


# --- Stage 4/4: agent-to-agent over HTTP (pattern 6) ------------------------


def illustrate_remote(headline: str, keywords: list[str]) -> str:
    """Calls the illustration agent from patterns/06_agent_to_agent_http as
    a completely separate process, the same way any other team's system
    would: discover its agent card, then POST to the task endpoint it names.
    """
    tracing.step("studio", f"stage 4/4: calling remote illustration agent at {ILLUSTRATION_AGENT_URL}")
    card_response = httpx.get(f"{ILLUSTRATION_AGENT_URL}/.well-known/agent.json", timeout=10.0)
    card_response.raise_for_status()
    endpoint = ILLUSTRATION_AGENT_URL + card_response.json()["task_endpoint"]
    task_response = httpx.post(endpoint, json={"headline": headline, "keywords": keywords}, timeout=30.0)
    task_response.raise_for_status()
    return task_response.json()["svg"]


# --- Orchestration -----------------------------------------------------------


def run(topic: str, audience: str = "internal") -> dict:
    tracing.system(f"=== Marketing Content Studio: topic={topic!r} audience={audience!r} ===")
    started = time.perf_counter()

    draft = research_and_draft(topic, audience)
    approved = critique_and_revise(draft)
    localized = localize(approved)

    headline = approved.split(".")[0]
    try:
        svg = illustrate_remote(headline, topic.split())
    except httpx.ConnectError:
        tracing.system(
            "Could not reach the illustration agent. Start it first, in another "
            "terminal, from the repo root:\n"
            "  PYTHONPATH=. uvicorn illustration_agent_service:app "
            "--app-dir patterns/06_agent_to_agent_http --port 8001"
        )
        raise

    elapsed = time.perf_counter() - started
    tracing.system(f"=== Studio pipeline complete in {elapsed:.2f}s ===")

    OUTPUT_DIR.mkdir(exist_ok=True)
    poster_path = OUTPUT_DIR / "poster.svg"
    poster_path.write_text(svg)

    package = {
        "topic": topic,
        "audience": audience,
        "approved_copy": approved,
        "localized_copy": localized,
        "poster_svg_path": str(poster_path),
    }
    (OUTPUT_DIR / "content_package.json").write_text(json.dumps(package, indent=2))
    return package


if __name__ == "__main__":
    cli_args = sys.argv[1:]
    topic = cli_args[0] if cli_args else "our excellent on-the-job training"
    audience = cli_args[1] if len(cli_args) > 1 else "internal"

    content_package = run(topic, audience)
    print("\n=== CONTENT PACKAGE ===")
    print(json.dumps(content_package, indent=2))
